field.field.*.*.*.third_party.field_autovalue:
  type: mapping
  label: 'Field Autovalue settings on the Field Config entities'
  mapping:
    autovalue:
      type: string
      label: 'Autovalue plugin machine name'
